name: Lint
description: |-
  Run lint checks in the workspace.

inputs:
  apply:
    description: |-
      Instead of running checks, apply changes.
    default: 'false'
  eslint:
    description: |-
      Check sources with ESLint.
    default: 'false'

runs:
  using: composite

  steps:
    - name: ESLint
      shell: bash
      if: fromJson(inputs.eslint)
      run: |
        pnpm eslint ${{ fromJson(inputs.apply) == 'true' && '--fix' || ''}} .
