name: Lint
description: |-
  Run lint checks in the workspace.

inputs:
  apply:
    description: |-
      Instead of running checks, apply changes.
    default: 'false'

runs:
  using: composite

  steps:
    - name: Stub
      shell: bash
      run: echo "stub"
