name: Lint
description: |-
  Run lint checks in the workspace.

inputs:
  apply:
    description: |-
      Instead of running checks, apply changes.
    default: 'false'
  eslint:
    description: |-
      Check sources with ESLint.
    default: 'false'
  prettier:
    description: |-
      Check sources with Prettier.
    default: 'false'
  typescript:
    description: |-
      Run TypeScript type checks.
    default: 'false'

runs:
  using: composite

  steps:
    - name: ESLint
      shell: bash
      if: fromJson(inputs.eslint)
      run: |
        pnpm eslint ${{ fromJson(inputs.apply) == 'true' && '--fix' || ''}} .

    - name: Prettier
      shell: bash
      if: fromJson(inputs.prettier)
      run: |
        pnpm prettier ${{ fromJson(inputs.apply) == 'true' && '--write' || '--check'}} .

    - name: TypeScript
      shell: bash
      if: fromJson(inputs.typescript) && !fromJson(inputs.apply)
      run: |
        pnpm tsc --build .
