name: Packages

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
      registry-url:
        type: string
        default: https://registry.npmjs.org
        required: true
      scope:
        type: string
        required: false
    secrets:
      NPM_TOKEN:
        required: true
      REPO_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup PNPM
        uses: langri-sha/github/actions/pnpm@v0.4.0
        with:
          always-auth: true
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.scope }}

      - name: Configure Git user
        uses: langri-sha/github/actions/github-action-bot-git-user@v0.4.0

      - name: Build composite projects
        run: pnpm tsc --build .

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx beachball@2.43.1 publish \
            --access public \
            --message "feat(beachball): Publish packages" \
            --new \
            --yes
